(() => {
 const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>Array.from(root.querySelectorAll(q));
 const overlay=$('.menu'),toggle=$('.menu-button'),close=$('.menu-close');
 const setMenu=(v)=>{if(!overlay)return;overlay.classList.toggle('open',v);overlay.setAttribute('aria-hidden',String(!v));document.body.style.overflow=v?'hidden':'';toggle?.setAttribute('aria-expanded',String(v)); if(v)close?.focus();};
 toggle?.addEventListener('click',()=>setMenu(true));close?.addEventListener('click',()=>setMenu(false));$$('.menu a').forEach(x=>x.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));
 const contact=$('#contact-form');contact?.addEventListener('submit',e=>{e.preventDefault();let data=new FormData(contact);const email=(window.B2W_CONTACT_EMAIL||'').trim();const msg=`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nInterest: ${data.get('interest')}\n\n${data.get('message')}`;if(!email){$('#contact-result').textContent='Form delivery is not configured yet. Connect an inbox or form endpoint before launch.';return;}window.location.href=`mailto:${email}?subject=${encodeURIComponent('B2W website inquiry — '+data.get('interest'))}&body=${encodeURIComponent(msg)}`;$('#contact-result').textContent='Opening your email app to send the message.';});
 const seed=[{name:'Sam R.',project:'Oak Street',amount:420,status:'Due Friday'},{name:'Maria L.',project:'Union Renovation',amount:680,status:'Due Friday'},{name:'Chris T.',project:'Oak Street',amount:350,status:'Review'}];let workers=seed.map(x=>({...x}));let activity=[{text:'4 hours added to Oak Street',source:'Sam R. · WhatsApp',state:'Pending'},{text:'Material delivery received',source:'Maria L. · Text',state:'Pending'},{text:'Friday shift submitted',source:'Chris T. · WhatsApp',state:'Pending'}];
 const money=x=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
 function renderPayroll(){const parent=$('#payroll-list');if(!parent)return;parent.innerHTML=workers.map((w,i)=>`<div class="demo-row"><div><strong>${escapeHTML(w.name)}</strong><div class="muted">${escapeHTML(w.project)} · ${escapeHTML(w.status)}</div></div><input aria-label="Amount due for ${escapeHTML(w.name)}" data-worker="${i}" type="number" min="0" step="1" value="${w.amount}"/><span class="chip">${money(w.amount)}</span></div>`).join('');$('#payroll-total').textContent=money(workers.reduce((a,w)=>a+Number(w.amount||0),0));$('#payroll-count').textContent=workers.length+' payments';$$('[data-worker]',parent).forEach(el=>el.addEventListener('change',()=>{workers[Number(el.dataset.worker)].amount=Math.max(0,Number(el.value)||0);renderPayroll()}));}
 function renderActivity(){const target=$('#activity-list');if(!target)return;target.innerHTML=activity.map((a,i)=>`<div class="demo-row"><div><strong>${escapeHTML(a.text)}</strong><div class="muted">${escapeHTML(a.source)} · ${escapeHTML(a.state)}</div></div><button class="icon-button approve" data-approve="${i}" title="Approve" aria-label="Approve ${escapeHTML(a.text)}">✓</button><button class="icon-button reject" data-reject="${i}" title="Reject" aria-label="Reject ${escapeHTML(a.text)}">×</button></div>`).join('');$$('[data-approve]',target).forEach(b=>b.addEventListener('click',()=>{activity[+b.dataset.approve].state='Approved';renderActivity()}));$$('[data-reject]',target).forEach(b=>b.addEventListener('click',()=>{activity[+b.dataset.reject].state='Rejected';renderActivity()}));}
 function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 $$('.tab[data-view]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;$$('.tab[data-view]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==v)}));$('#add-worker')?.addEventListener('click',()=>{workers.push({name:'New worker',project:'Unassigned',amount:0,status:'Draft'});renderPayroll()});renderPayroll();renderActivity();
 const steps=['Capture','Estimate','Scope','Visualize','Present'];let current=0;
 function renderClara(){const root=$('#clara-workflow');if(!root)return;$$('[data-step]').forEach(b=>{b.classList.toggle('active',+b.dataset.step===current);b.setAttribute('aria-current',+b.dataset.step===current?'step':'false')});const note=$('#voice-description')?.value||'Replace damaged ceiling tiles, repair the entry flooring, and refresh the lobby.';const html=[`<p class="eyebrow">01 / Voice capture</p><p>Record a property walk-through or enter the site notes below.</p><label class="field" style="margin-top:24px">Site notes<textarea id="voice-description">${escapeHTML(note)}</textarea></label><p class="muted" style="margin-top:14px">Concept demo: no audio is recorded or uploaded.</p>`,`<p class="eyebrow">02 / Preliminary estimate</p><p>Organize the description into cost items, assumptions, and questions for contractor verification.</p><div class="rule"></div><div class="metric"><span>Ceiling repair</span><strong>Needs measured area</strong></div><div class="metric"><span>Entry flooring</span><strong>Needs materials / area</strong></div><div class="metric"><span>Lobby refresh</span><strong>Needs finish specification</strong></div><p class="muted" style="margin-top:20px">No prices are fabricated. Contractor quotes and measurements are required.</p>`,`<p class="eyebrow">03 / Project scope</p><p>Convert the notes into an editable scope of work with responsibilities and verification checkpoints.</p><div class="rule"></div><p>Document site conditions → measure quantities → agree finishes → request contractor quotes → confirm schedule.</p>`,`<p class="eyebrow">04 / Concept exploration</p><p>Develop visual directions and store selected concepts next to scope decisions.</p><div class="grid-2" style="margin-top:26px"><div class="feature-art" style="min-height:145px;background:linear-gradient(145deg,#f1e7fc,#9f87b1)">Warm natural materials</div><div class="feature-art" style="min-height:145px;background:linear-gradient(145deg,#273e58,#a498ce);color:white">Contemporary contrast</div></div><p class="muted" style="margin-top:12px">Illustrative palettes, not generated renovation renderings.</p>`,`<p class="eyebrow">05 / Shared presentation</p><p>Bring the scope, assumptions, concept directions, and decisions together for owners, investors, and builders.</p><div class="rule"></div><div class="stamp"><span class="seal">◈</span> CLARA · CONCEPT / NOT VERIFIED · REV 01</div><p class="muted" style="margin-top:18px">Concept workflow. Export and team collaboration are planned features.</p>`];root.innerHTML=html[current];}
 $$('[data-step]').forEach(b=>b.addEventListener('click',()=>{current=+b.dataset.step;renderClara()}));$('#next-step')?.addEventListener('click',()=>{current=(current+1)%steps.length;renderClara()});renderClara();
})();
