"use strict";
const el=id=>document.getElementById(id);
const store="b2w-brand-assets-review-v1";
let items=[],visible=[],active="",site="All",votes={};
try{votes=JSON.parse(localStorage.getItem(store)||"{}")}catch{votes={}}
let toastTimer;
function notify(x){el("toast").textContent=x;el("toast").hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el("toast").hidden=true,2500)}
function vote(id){return votes[id]||"pending"}
function voteText(x){return x==="approved"?"Approved":x==="revise"?"Needs changes":"Review pending"}
function save(){try{localStorage.setItem(store,JSON.stringify(votes))}catch{notify("Local reviews could not be stored")}el("total-reviewed").textContent=Object.keys(votes).length+" of "+items.length+" reviewed"}
function ref(x){return "./"+x}
function sections(){const s=el("section"),p=s.value;s.replaceChildren(new Option("All sections",""));let arr=[...new Set(items.filter(a=>site==="All"||(site==="Shared"?a.section_index===0:a.site===site&&a.section_index>0)).map(a=>a.section))];arr.forEach(v=>s.add(new Option(v,v)));s.value=arr.includes(p)?p:""}
function chooseSite(x){site=x;el("sites").querySelectorAll("button").forEach(b=>{let v=b.dataset.site===x;b.classList.toggle("on",v);b.setAttribute("aria-pressed",String(v))});sections();filter()}
function filter(){let q=el("q").value.trim().toLowerCase(),section=el("section").value,layer=el("layer").value,status=el("status-filter").value;
visible=items.filter(a=>(site==="All"||(site==="Shared"?a.section_index===0:a.site===site&&a.section_index>0))&&(!section||a.section===section)&&(!layer||Number(a.layer_index)===Number(layer))&&(!status||vote(a.id)===status)&&(!q||[a.id,a.site,a.title,a.section,a.context,a.trigger,a.audience,a.claim,a.surface].join(" ").toLowerCase().includes(q)));
if(!visible.some(a=>a.id===active))active=visible[0]?.id||"";
el("found").textContent=visible.length+" assets";el("empty").hidden=!!visible.length;renderGrid();renderSelected()}
function renderGrid(){const f=document.createDocumentFragment();for(let a of visible){let b=document.createElement("button");b.type="button";b.className="tile";b.setAttribute("aria-current",String(a.id===active));b.dataset.id=a.id;let img=document.createElement("img");img.loading="lazy";img.alt="";img.src=ref(a.svg);let info=document.createElement("span");info.className="tile-info";for(const t of [a.title,a.id+" / "+a.site,voteText(vote(a.id))]){let span=document.createElement("span");span.textContent=t;info.append(span)}b.append(img,info);b.onclick=()=>select(a.id,true);f.append(b)}el("cards").replaceChildren(f)}
function renderSelected(){let a=visible.find(x=>x.id===active);el("viewer").hidden=!a;if(!a)return;el("preview").hidden=false;el("broken").hidden=true;el("preview").src=ref(a.svg);el("preview").alt=a.alt||a.title;
el("asset-code").textContent=a.id;el("asset-status").textContent=voteText(vote(a.id));el("brand-name").textContent=a.site;el("title").textContent=a.title;
let facts=[["Website",a.site],["Placement",a.surface.replaceAll("-"," ")],["Section",a.section],["Detail",a.layer],["Appears",a.trigger],["Audience",a.audience],["Claim",a.claim]];
el("facts").replaceChildren(...facts.map(([k,v])=>{let d=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=k;dd.textContent=v;d.append(dt,dd);return d}));
el("count").textContent=String(visible.findIndex(x=>x.id===active)+1).padStart(2,"0")+" / "+String(visible.length).padStart(2,"0");
el("svg").href=ref(a.svg);el("svg").download=a.id+".svg";el("prev").disabled=el("next").disabled=visible.length<=1;el("approve").setAttribute("aria-pressed",String(vote(a.id)==="approved"));el("revise").setAttribute("aria-pressed",String(vote(a.id)==="revise"))}
function select(id,scroll=false){if(!visible.some(x=>x.id===id))return;active=id;renderSelected();el("cards").querySelectorAll(".tile").forEach(b=>b.setAttribute("aria-current",String(b.dataset.id===id)));const url=new URL(location.href);url.searchParams.set("asset",id);history.replaceState({id},"",url);if(scroll)el("viewer").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})}
function move(n){if(!visible.length)return;let pos=visible.findIndex(x=>x.id===active);select(visible[(pos+n+visible.length)%visible.length].id)}
function decide(x){if(!active)return;if(x==="pending")delete votes[active];else votes[active]=x;save();filter();notify(x==="pending"?"Review reset":voteText(x)+" saved locally")}
async function prompt(){let a=visible.find(x=>x.id===active);if(!a)return;el("prompt-title").textContent=a.title;el("prompt-code").textContent=a.id;el("prompt-source").href=ref(a.prompt);el("prompt-body").textContent="Loading…";el("dialog").showModal();try{let r=await fetch(ref(a.prompt));if(!r.ok)throw Error("HTTP "+r.status);el("prompt-body").textContent=await r.text()}catch(e){el("prompt-body").textContent=a.full_prompt||"Prompt unavailable: "+e.message}}
async function copy(x){try{await navigator.clipboard.writeText(x);notify("Copied")}catch{notify("Clipboard unavailable")}}
function exportVotes(){let doc={generated:new Date().toISOString(),note:"Local review only",decisions:items.filter(a=>votes[a.id]).map(a=>({id:a.id,site:a.site,title:a.title,review:votes[a.id]}))},url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="b2w-asset-reviews.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function handlers(){el("sites").onclick=e=>{let b=e.target.closest("[data-site]");if(b)chooseSite(b.dataset.site)};el("q").oninput=filter;for(let x of ["section","layer","status-filter"])el(x).onchange=filter;el("prev").onclick=()=>move(-1);el("next").onclick=()=>move(1);el("approve").onclick=()=>decide("approved");el("revise").onclick=()=>decide("revise");el("clear-review").onclick=()=>decide("pending");el("prompt").onclick=prompt;el("close").onclick=()=>el("dialog").close();el("copy-prompt").onclick=()=>copy(el("prompt-body").textContent);el("link").onclick=()=>{let url=new URL(location.href);url.searchParams.set("asset",active);copy(url.toString())};el("export").onclick=exportVotes;el("clear-filters").onclick=()=>{el("q").value=el("section").value=el("layer").value=el("status-filter").value="";chooseSite("All")};el("preview").onerror=()=>{el("preview").hidden=true;el("broken").hidden=false};document.addEventListener("keydown",e=>{if(el("dialog").open||["INPUT","TEXTAREA","SELECT"].includes(e.target.tagName))return;if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)})}
async function init(){handlers();try{let r=await fetch("./02-prompt-database/prompts.json");if(!r.ok)throw Error("HTTP "+r.status);items=(await r.json()).filter(a=>a.id&&a.svg);save();sections();filter();let wanted=new URL(location.href).searchParams.get("asset"),a=items.find(x=>x.id===wanted);if(a){chooseSite(a.section_index===0?"Shared":a.site);select(a.id)}}catch(e){el("viewer").hidden=true;el("empty").hidden=false;el("empty").textContent="Unable to load assets: "+e.message}}
init();